# Generated by Django 3.1.7 on 2021-02-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=15)),
                ('year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='post created date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='post updated date')),
            ],
        ),
    ]
